# Generated by Django 4.1.5 on 2023-01-08 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasker", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="task_about",
            options={"verbose_name": "Задание", "verbose_name_plural": "Задания"},
        ),
        migrations.AddField(
            model_name="task_about",
            name="is_conplete",
            field=models.BooleanField(default=False, verbose_name="Завершено"),
        ),
        migrations.AlterField(
            model_name="task_about",
            name="name_task",
            field=models.CharField(max_length=100, verbose_name="Название задания"),
        ),
    ]
