# Generated by Django 4.1.5 on 2023-01-09 02:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tasker", "0002_alter_task_about_options_task_about_is_conplete_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="task_about",
            old_name="name_task",
            new_name="title",
        ),
    ]
