# Generated by Django 4.1.5 on 2023-01-09 04:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tasker", "0003_rename_name_task_task_about_title"),
    ]

    operations = [
        migrations.RenameField(
            model_name="task_about",
            old_name="is_conplete",
            new_name="is_complite",
        ),
    ]
