# Generated by Django 4.1.5 on 2023-01-09 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasker", "0004_rename_is_conplete_task_about_is_complite"),
    ]

    operations = [
        migrations.AddField(
            model_name="task_about",
            name="title21",
            field=models.CharField(
                default="gawgbg", max_length=150, verbose_name="Название задания"
            ),
        ),
    ]
