# Generated by Django 4.1.5 on 2023-01-22 13:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tasker', '0009_alter_task_about_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task_about',
            name='user',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
