# Generated by Django 4.1.5 on 2023-01-13 05:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tasker", "0010_task_user_alter_task_about_user"),
    ]

    operations = [
        migrations.RenameField(
            model_name="task_user",
            old_name="user",
            new_name="users",
        ),
    ]
